#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V 

bspc config border_width         0
bspc config window_gap           8

bspc config split_ratio           0.52
bspc config borderless_monocle    true
bspc config gapless_monocle       true
bspc config focus_follows_pointer true

# bspc rule -a mplayer2 state=floating

bspc rule -a Emacs state=tiled

${HOME}/.fehbg
${HOME}/.config/polybar/launch.sh 

xsetroot -cursor_name left_ptr &

setxkbmap -model abnt -layout us -variant intl -option caps:escape

picom --experimental-backends &

wmname LG3D

start-pulseaudio-x11


